apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080         # Service port
    targetPort: 8080   # Container port
    nodePort: 30036    # External port (range: 30000–32767)
